# Application support modules for the Discord bot runtime.
# Re-export command permission symbols for backwards compatibility so that
# `from app import COMMAND_PERMISSION_DEFAULTS` and similar legacy imports
# used across bot.py and the test suite continue to resolve.
from app.command_permissions import (  # noqa: F401
    ADMIN_ONLY_COMMAND_KEYS,
    DEFAULT_ALLOWED_ROLE_NAMES,
    MODERATOR_ONLY_COMMAND_KEYS,
    COMMAND_PERMISSION_DEFAULT_POLICY_ADMINISTRATOR,
    COMMAND_PERMISSION_DEFAULT_POLICY_ALLOWED_NAMES,
    COMMAND_PERMISSION_DEFAULT_POLICY_MODERATOR_IDS,
    COMMAND_PERMISSION_DEFAULT_POLICY_PUBLIC,
    COMMAND_PERMISSION_DEFAULTS,
    COMMAND_PERMISSION_MODE_CUSTOM_ROLES,
    COMMAND_PERMISSION_MODE_DEFAULT,
    COMMAND_PERMISSION_MODE_DISABLED,
    COMMAND_PERMISSION_MODE_PUBLIC,
    COMMAND_PERMISSION_METADATA,
    COMMAND_PERMISSION_POLICY_LABELS,
    can_use_command,
    ensure_interaction_command_access,
    ensure_prefix_command_access,
    is_random_choice_eligible,
    load_command_permission_rules,
    load_honeypot_entries,
    member_has_any_role_id,
    normalize_command_permission_rule,
    normalize_honeypot_record,
    normalize_permission_mode,
    normalize_role_ids,
    resolve_command_permission_state,
    reply_with_default_visibility,
    run_web_get_command_permissions,
    run_web_update_command_permissions,
    save_command_permission_rules,
    send_safe_interaction_message,
    send_safe_interaction_modal,
    build_command_permission_denied_message,
    build_command_permissions_web_payload,
    get_text_channel,
    log_interaction,
)
