name: Secret Scan

on:
  pull_request:
    branches:
      - main
      - beta
  push:
    branches:
      - main
      - beta
  workflow_call:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

permissions:
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09  # 5
        with:
          fetch-depth: 0

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7  # 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
